CREATE TABLE IF NOT EXISTS USER_ACCOUNT
(
    EMAIL    VARCHAR(30)  PRIMARY KEY NOT NULL,
    USER_NAME VARCHAR(30) NOT NULL,
    GENDER   VARCHAR(1)  NOT NULL,
    COUNTRY   VARCHAR(30) NOT NULL,
    PASSWORD  VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS GAME
(
    ID       INTEGER AUTO_INCREMENT,
    EMAIL    VARCHAR(30) NOT NULL,
    NUMBER    INTEGER  NOT NULL,
    ATTEMPTS INTEGER  NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);